CREATE TABLE CONTACTS
(
    _ID integer AUTO_INCREMENT PRIMARY KEY NOT NULL,
    FIRST_NAME varchar(60) NOT NULL,
    LAST_NAME varchar(60) NOT NULL,
    BIRTH_DATE date,
    DESCRIPTION varchar(2000),
    PHOTO blob,
    VERSION integer DEFAULT 0 NOT NULL
);
CREATE UNIQUE INDEX UQ_CONTACT_IND ON CONTACTS (FIRST_NAME, LAST_NAME)